language: php
php:
    - '7.3'
    - nightly

matrix:
    allow_failures:
        - php: nightly

install: composer install

script:
    - mkdir -p builds/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml